### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by tandooribeer** [breuerfelix/jinsta#18]
I do not belong to tech background and consider me a noob in this field. Can someone please make a introductory video about how to install and do basic configuration of this tool. I was earlier using instapy but that seems to be lagging behind now. 

I have read the read me file and installed node.js as well as run the basic commands now how can i set parameters to use this tool effectively, TIA

**Comment by breuerfelix** [comment]
hey :)

i wont make a detailed video now because the project is just in pre alpha stage. it could be, that this setup will change in 1-2 weeks so it doesnt make sense to put in alot of work for the video right now :)

the architecture is not final, but i hope that this will be in about 2 weeks from now. once the architecture is final, i will do a video, or i hope someone else will do that !
